const parts = {
  mcu:{name:'ESP32-S3 Controller', sub:'Wireless MCU · 8 MB flash', tag:'WIRELESS MCU', value:'4.2 × 3.3 mm', copy:'The central brain of the board. It handles Wi‑Fi communication, sensor readings, and your application logic in one compact module.', glyph:'MCU'},
  sensor:{name:'BME280 Environmental Sensor', sub:'Temperature · humidity · pressure', tag:'I²C SENSOR', value:'2.5 × 2.5 mm', copy:'This low-power sensor measures temperature, humidity, and air pressure. It is positioned away from heat sources for more accurate ambient readings.', glyph:'SEN'},
  usb:{name:'USB-C Power & Data', sub:'5 V input · USB 2.0', tag:'USB-C', value:'8.9 × 7.4 mm', copy:'USB-C provides convenient programming and charging power. Its protected footprint is placed at the board edge for reliable cable access.', glyph:'USB'},
  battery:{name:'LiPo Battery Connector', sub:'1-cell · JST-PH', tag:'POWER INPUT', value:'7.0 × 5.0 mm', copy:'The polarized battery connector makes the board portable. Dedicated nearby protection and regulation keep its power delivery safe and stable.', glyph:'BAT'},
  led:{name:'Status LED', sub:'Green · user programmable', tag:'USER INTERFACE', value:'1.6 × 0.8 mm', copy:'A small indicator LED gives instant feedback for power, charging, network status, or your own firmware events without adding bulk.', glyph:'LED'},
  regulator:{name:'3.3V Voltage Regulator', sub:'Low-noise buck regulator', tag:'POWER MANAGEMENT', value:'3.0 × 3.0 mm', copy:'This regulator converts USB or battery power into the clean 3.3V rail required by the MCU and sensor. Short traces reduce electrical noise.', glyph:'3V3'},
  antenna:{name:'2.4 GHz PCB Antenna', sub:'Wi‑Fi / Bluetooth', tag:'RF ANTENNA', value:'15.0 × 3.0 mm', copy:'The edge-mounted antenna provides wireless range without an external part. Its clear keep-out zone protects RF performance.', glyph:'ANT'}
};
const defaultParts = Object.fromEntries(Object.entries(parts).map(([id, value])=>[id,{...value}]));
const joystickParts = {
  mcu:{name:'RP2040 Controller', sub:'Dual-core MCU · native USB', tag:'GAME CONTROLLER MCU', value:'7.0 × 7.0 mm', copy:'The RP2040 reads the joystick axes, handles buttons, and presents the finished controller as a USB HID device to a computer or console.', glyph:'MCU'},
  sensor:{name:'ALPS Alpine RKJXV1224005', sub:'2-axis analog joystick · push switch', tag:'JOYSTICK', value:'14.0 × 17.0 mm', copy:'A genuine ALPS Alpine 2-axis joystick module with an integrated press switch. Two analog lines carry X/Y position, and the switch adds a third digital input.', glyph:'JOY'},
  usb:{name:'USB-C Receptacle', sub:'USB 2.0 data · 5 V power', tag:'USB-C', value:'8.9 × 7.4 mm', copy:'The USB-C connector powers the handheld controller and carries its USB HID data signal. It remains edge-mounted for strain relief and easy access.', glyph:'USB'},
  battery:{name:'USBLC6-2SC6 ESD Protection', sub:'USB data-line protection', tag:'ESD PROTECTION', value:'2.9 × 1.6 mm', copy:'This protection array absorbs electrostatic discharge from the exposed USB connector before it can reach the controller.', glyph:'ESD'},
  led:{name:'SK6812MINI-E RGB Status LED', sub:'Addressable status indicator', tag:'USER FEEDBACK', value:'3.5 × 3.5 mm', copy:'A tiny addressable RGB LED reports pairing, charging, or game status with a single MCU data pin.', glyph:'RGB'},
  regulator:{name:'TPS63031 Power Regulator', sub:'Buck-boost · 3.3 V rail', tag:'POWER MANAGEMENT', value:'3.0 × 3.0 mm', copy:'This buck-boost regulator maintains a steady 3.3 V supply as battery voltage changes, which keeps joystick readings stable.', glyph:'PWR'},
  antenna:{name:'Tactile Button Array', sub:'Four low-profile action buttons', tag:'PLAYER INPUT', value:'6.0 × 6.0 mm', copy:'These tactile switch footprints provide compact, responsive action inputs without taking space from the main joystick.', glyph:'BTN'}
};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let selected='mcu', zoom=1, dragging=false, componentDrag=null, boardResize=null, start={x:0,y:0}, angles={x:43,z:-19};
const examplePrompts={controller:'A classic 4-button joystick with a rechargeable protected 3.7 V LiPo battery, USB-C charging, RP2040 native USB controller, 2-axis analog joystick, four momentary push buttons, USB-C ESD protection, 3.3 V regulator, decoupling capacitors, and a charging status LED.',humidDetector:'A USB-C rechargeable humidity and temperature detector with a protected LiPo battery, BME280 environmental sensor, status LED, USB-C charging circuit, 3.3 V regulator, decoupling capacitors, and ESD protection.'};
const componentList=$('#componentList'), library=$('#library');
const calloutAction=document.createElement('p');calloutAction.className='component-action';$('#calloutCopy').after(calloutAction);new MutationObserver(()=>{calloutAction.textContent=`What it does: ${$('#calloutCopy').textContent}`}).observe($('#calloutCopy'),{childList:true,characterData:true,subtree:true});calloutAction.textContent=`What it does: ${$('#calloutCopy').textContent}`;
function renderParts(){componentList.innerHTML='';library.innerHTML='';Object.entries(parts).forEach(([id,p])=>{const row=document.createElement('div');row.className='component-row '+(id===selected?'active':'');row.dataset.part=id;row.innerHTML=`<span class="comp-glyph">${p.glyph}</span><span><strong>${p.name}</strong><small>${p.sub}</small></span><b>✓</b>`;componentList.append(row);const lib=document.createElement('div');lib.className='library-item';lib.dataset.part=id;lib.innerHTML=`<i class="lib-icon"></i><span>${p.glyph}</span>`;library.append(lib)})}
function select(id){if(!parts[id])return;selected=id;const p=parts[id];$('#calloutTitle').textContent=p.name;$('#calloutIdentity').textContent=`What it is: ${p.sub || p.name}.`;$('#calloutCopy').textContent=p.copy;$('#calloutTag').textContent=p.tag;$('#calloutValue').textContent=p.value;$('#callout').classList.remove('hidden');$('#leaderPath').closest('.leader').classList.remove('hidden');$$('.pcb-part').forEach(x=>x.classList.toggle('selected',x.dataset.part===id));$$('.component-row').forEach(x=>x.classList.toggle('active',x.dataset.part===id));const el=$(`.pcb-part[data-part="${id}"]`),scene=$('#pcbScene'),rect=scene.getBoundingClientRect(),part=el.getBoundingClientRect();const x=((part.left+part.width/2-rect.left)/rect.width*1000).toFixed(0),y=((part.top+part.height/2-rect.top)/rect.height*700).toFixed(0);$('#leaderDot').setAttribute('cx',x);$('#leaderDot').setAttribute('cy',y);$('#leaderPath').setAttribute('d',`M ${x} ${y} C ${Math.min(+x+130,750)} ${y}, 715 145, 820 145`);updateConnections()}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function setBoard(){ $('#boardWrap').style.transform=`translate(-50%,-50%) scale(${zoom}) rotateX(${angles.x}deg) rotateZ(${angles.z}deg)` }
const boardWrap=$('#boardWrap');['top','right','bottom','left'].forEach(edge=>{const handle=document.createElement('div');handle.className=`resize-handle resize-${edge}`;handle.setAttribute('aria-label',`Resize board from ${edge} edge`);handle.addEventListener('pointerdown',event=>{event.preventDefault();event.stopPropagation();boardResize={edge,pointerId:event.pointerId,x:event.clientX,y:event.clientY,width:boardWrap.offsetWidth,height:boardWrap.offsetHeight};handle.setPointerCapture(event.pointerId);document.body.classList.add('resizing-board')});boardWrap.append(handle)});
document.addEventListener('pointermove',event=>{if(!boardResize||event.pointerId!==boardResize.pointerId)return;const horizontal=/left|right/.test(boardResize.edge),delta=horizontal?event.clientX-boardResize.x:event.clientY-boardResize.y,sign=/left|top/.test(boardResize.edge)?-1:1;const size=Math.max(horizontal?465:320,(horizontal?boardResize.width:boardResize.height)+delta*sign);if(horizontal)boardWrap.style.width=`${size}px`;else{boardWrap.style.height=`${size}px`;boardWrap.style.aspectRatio='auto'}updateConnections()});
document.addEventListener('pointerup',event=>{if(!boardResize||event.pointerId!==boardResize.pointerId)return;boardResize=null;document.body.classList.remove('resizing-board')});
selected=null;$('#board').classList.add('empty');$('#callout').classList.add('hidden');$('#leaderPath').closest('.leader').classList.add('hidden');$('#prompt').value='';componentList.innerHTML='<div class="empty-state">Describe what you want to build, then generate a fresh component plan.</div>';library.innerHTML='';$('#componentCount').textContent='0';$('#checkStatus').textContent='Waiting';$('.strip-title span').textContent='0 placed';$('.board-status').innerHTML='<span><i class="pulse"></i> Ready for a new PCB</span>';
const examples=document.createElement('div');examples.className='example-links';examples.innerHTML='<span>Examples</span><button type="button" data-example="controller">Controller</button><button type="button" data-example="humidDetector">HumidDetector</button>';$('#generateBtn').after(examples);examples.addEventListener('click',event=>{const name=event.target.dataset.example;if(!name)return;$('#prompt').value=examplePrompts[name];$('#generateBtn').click()});
document.addEventListener('click',e=>{const id=e.target.closest('[data-part]')?.dataset.part;if(id)select(id)});
$('#closeCallout').onclick=()=>{$('#callout').classList.add('hidden');$('#leaderPath').closest('.leader').classList.add('hidden')};
$('#zoomIn').onclick=()=>{zoom=Math.min(1.35,zoom+.1);setBoard()};$('#zoomOut').onclick=()=>{zoom=Math.max(.7,zoom-.1);setBoard()};$('#resetView').onclick=()=>{zoom=1;angles={x:43,z:-19};setBoard();toast('View reset')};
$('#gridBtn').onclick=e=>{e.currentTarget.classList.toggle('active');$('#pcbScene').classList.toggle('grid-off')};$('#fitBtn').onclick=()=>$('#resetView').click();$('#orbitBtn').onclick=e=>e.currentTarget.classList.toggle('active');
const scene=$('#pcbScene');scene.addEventListener('pointerdown',e=>{if(e.target.closest('.pcb-part,.component-callout,button'))return;dragging=true;start={x:e.clientX,y:e.clientY};scene.setPointerCapture(e.pointerId)});scene.addEventListener('pointermove',e=>{if(!dragging)return;angles.z+= (e.clientX-start.x)*.12;angles.x=Math.max(22,Math.min(62,angles.x-(e.clientY-start.y)*.12));start={x:e.clientX,y:e.clientY};setBoard()});scene.addEventListener('pointerup',()=>dragging=false);scene.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.7,Math.min(1.35,zoom-(e.deltaY*.0008)));setBoard()},{passive:false});
$('#generateBtn').onclick=async()=>{const btn=$('#generateBtn'),progress=$('#generationProgress'),text=$('#generateText'),bar=$('#progressBar'),pct=$('#progressPct'),label=$('#progressText'),isJoystick=/joystick|gamepad|controller|thumbstick/i.test($('#prompt').value);btn.disabled=true;progress.classList.remove('hidden');$('#board').classList.remove('empty');Object.assign(parts,isJoystick?joystickParts:defaultParts);const steps=['Understanding requirements…',isJoystick?'Matching verified joystick components…':'Selecting components…','Routing 46 connections…','Checking manufacturability…','Finalizing compact layout…'];for(let i=0;i<steps.length;i++){label.textContent=steps[i];const val=18+i*20;bar.style.width=val+'%';pct.textContent=val+'%';await new Promise(r=>setTimeout(r,480))}renderParts();select(isJoystick?'sensor':'mcu');$('.mcu .chip-label').textContent=isJoystick?'RP2040':'ESP32-S3';$('.sensor .sensor-body').textContent=isJoystick?'ALPS JOY':'BME280';$('#componentCount').textContent='7';if(isJoystick)toast('Joystick parts matched from the component catalog');bar.style.width='100%';pct.textContent='100%';text.textContent='PCB Generated';$('#checkStatus').textContent='4 passed';setTimeout(()=>{progress.classList.add('hidden');btn.disabled=false;text.textContent='Generate PCB';toast(isJoystick?'Controller layout generated with verified joystick parts':'New PCB layout generated — 14% more compact')},900)};
$('#resetPcbBtn').onclick=()=>{selected=null;$('#prompt').value='';$('#board').classList.add('empty');$('#callout').classList.add('hidden');$('#leaderPath').closest('.leader').classList.add('hidden');componentList.innerHTML='<div class="empty-state">Describe what you want to build, then generate a fresh component plan.</div>';library.innerHTML='';$('#componentCount').textContent='0';$('#checkStatus').textContent='Waiting';$('#optTitle').textContent='No layout yet';$('#optBadge').textContent='Ready';$('#optCopy').textContent='Start a new design to receive a compactness score and placement recommendations.';toast('PCB reset — ready for a new design')};
$('#optimizeBtn').onclick=async()=>{const b=$('#optimizeBtn');b.disabled=true;b.innerHTML='Optimizing placement…';await new Promise(r=>setTimeout(r,1100));$('#optTitle').textContent='96% compactness';$('#optBadge').textContent='Optimized';$('#optCopy').textContent='Parts re-placed to reduce board area by another 6% while preserving all clearances.';b.innerHTML='Layout optimized <span>✓</span>';toast('Optimization complete — board area reduced 6%')};
$('#shuffleBtn').onclick=()=>{toast('Component choices re-evaluated');$('#componentList').classList.add('pulse-list');setTimeout(()=>$('#componentList').classList.remove('pulse-list'),500)};
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')$('#generateBtn').click()});

document.addEventListener('pointerdown',event=>{const part=event.target.closest('.pcb-part');if(!part)return;event.preventDefault();componentDrag={part,pointerId:event.pointerId};part.setPointerCapture(event.pointerId);part.classList.add('dragging');select(part.dataset.part)});
document.addEventListener('pointermove',event=>{if(!componentDrag||event.pointerId!==componentDrag.pointerId)return;const board=$('#board'),rect=board.getBoundingClientRect();const x=Math.max(6,Math.min(94,(event.clientX-rect.left)/rect.width*100));const y=Math.max(8,Math.min(92,(event.clientY-rect.top)/rect.height*100));componentDrag.part.style.setProperty('--x',`${x}%`);componentDrag.part.style.setProperty('--y',`${y}%`);updateConnections();select(componentDrag.part.dataset.part)});
document.addEventListener('pointerup',event=>{if(!componentDrag||event.pointerId!==componentDrag.pointerId)return;componentDrag.part.classList.remove('dragging');componentDrag=null});

// Scalable plan generator: every requested capability becomes a separately placed footprint.
const catalogRules=[
  [/joystick|thumbstick/i,'ALPS Alpine RKJXV1224005','2-axis joystick + switch','JOY','input-part'],
  [/oled|display|screen/i,'SSD1306 OLED Display','128×64 I²C display','OLED','input-part'],
  [/gps|gnss/i,'u-blox MAX-M10S','GNSS receiver','GPS','input-part'],
  [/imu|accelerometer|gyroscope/i,'Bosch BMI270','6-axis IMU','IMU','input-part'],
  [/motor|h-bridge/i,'TI DRV8833','Dual motor driver','MTR','power-part'],
  [/bluetooth/i,'nRF52840','Bluetooth LE controller','BLE',''],
  [/wifi|wi-fi/i,'ESP32-S3','Wi‑Fi + BLE module','WIFI',''],
  [/battery|lipo|charging/i,'BQ24074','LiPo charger + power path','CHG','power-part'],
  [/temperature|humidity|pressure|environment/i,'BME280','Environmental sensor','SEN','input-part'],
  [/audio|speaker|microphone/i,'MAX98357A','I²S audio amplifier','AUD','power-part'],
  [/relay/i,'Omron G5LE Relay','Isolated load switch','RLY','power-part'],
  [/camera/i,'OV2640 Camera','2 MP image sensor','CAM','input-part'],
  [/sd card|microsd/i,'MicroSD Socket','Storage connector','SD','input-part'],
  [/\bled\b|status light|indicator/i,'Status LED','Power and status indicator','LED','input-part'],
  [/rp2040|native usb/i,'RP2040 USB controller','Native USB game controller MCU','MCU','']
];
function newPart(id,name,sub,glyph,kind=''){return {id,name,sub,glyph,kind,tag:'CATALOG MATCH',value:'Auto-sized',copy:`${name} was added to satisfy your request. Its footprint is spaced for electrical clearance, serviceability, and the shortest practical connection path.`}}
function buildPlan(prompt){const plan=[newPart('part-usb','USB-C charging & data port','Edge mounted · power + programming','USB','usb-port power-part')],lower=prompt.toLowerCase();catalogRules.forEach(([test,name,sub,glyph,kind])=>{if(test.test(prompt))plan.push(newPart(`part-${plan.length}`,name,sub,glyph,kind))});if(!plan.some(p=>/controller|MCU/.test(p.name)))plan.push(newPart(`part-${plan.length}`,'STM32G0 Controller','Main control and I/O','MCU',''));const buttonMatch=lower.match(/(\d+)\s*(?:push )?buttons?/);const buttonCount=Math.min(Number(buttonMatch?.[1]||(/button/.test(lower)?4:0)),48);for(let i=0;i<buttonCount;i++)plan.push(newPart(`part-${plan.length}`,`Tactile Button ${i+1}`,buttonCount>1?`Player input ${i+1} of ${buttonCount}`:'User input','BTN','input-part'));
  const known=/joystick|thumbstick|oled|display|screen|gps|gnss|imu|accelerometer|gyroscope|motor|h-bridge|bluetooth|wifi|wi-fi|battery|lipo|charging|temperature|humidity|pressure|environment|audio|speaker|microphone|relay|camera|sd card|microsd|button/.test(lower);
  if(!known&&prompt.trim())plan.push(newPart(`part-${plan.length}`,'Requested custom subsystem',prompt.trim().slice(0,54),'NEW','input-part'));
  return plan;
}
function renderGeneratedBoard(plan){const board=$('#board');board.className='board generated';const cols=Math.max(3,Math.ceil(Math.sqrt(Math.max(1,plan.length-1)*1.45))),rows=Math.ceil((plan.length-1)/cols),areaW=Math.max(42,cols*12+20),areaH=Math.max(32,rows*12+20);board.innerHTML=`<div class="generated-silk">KESH-CUSTOM · AUTO-PLACED</div><div class="generated-size">${areaW} × ${areaH} mm</div>`;const partMap={};plan.forEach((part,index)=>{let x,y;if(index===0){x=4;y=50}else{const n=index-1,col=n%cols,row=Math.floor(n/cols);x=18+(col/(Math.max(1,cols-1)))*64;y=16+(row/(Math.max(1,rows-1)))*68}partMap[part.id]={name:part.name,sub:part.sub,glyph:part.glyph,tag:part.tag,value:part.value,copy:part.copy};const el=document.createElement('button');el.className=`pcb-part generated-part ${part.kind}`;el.dataset.part=part.id;el.style.setProperty('--x',`${x}%`);el.style.setProperty('--y',`${y}%`);el.style.setProperty('--size',plan.length>24?'38px':plan.length>14?'46px':'58px');el.textContent=part.glyph;board.append(el);if(index>0){const trace=document.createElement('i');trace.className='generated-trace';trace.style.left='7%';trace.style.top=`${Math.max(18,Math.min(82,y))}%`;trace.style.width=`${Math.max(8,x-7)}%`;trace.style.transform=`rotate(${(y-50)*.18}deg)`;board.append(trace)}});Object.keys(parts).forEach(key=>delete parts[key]);Object.assign(parts,partMap);renderParts();$('#componentCount').textContent=String(plan.length);$('.strip-title span').textContent=`${plan.length} placed`;$('.board-status').innerHTML=`<span><i class="pulse"></i> Auto-routed · ${plan.length} parts</span><span>${areaW} × ${areaH} mm</span>`}
$('#generateBtn').onclick=async()=>{const prompt=$('#prompt').value.trim()||'Compact USB-C development board',plan=buildPlan(prompt),btn=$('#generateBtn'),progress=$('#generationProgress'),text=$('#generateText'),bar=$('#progressBar'),pct=$('#progressPct'),label=$('#progressText');btn.disabled=true;progress.classList.remove('hidden');const steps=['Reading design requirements…','Checking component catalog…',`Placing ${plan.length} footprints…`,'Routing protected power and data…','Checking layout clearance…'];for(let i=0;i<steps.length;i++){label.textContent=steps[i];const value=18+i*20;bar.style.width=value+'%';pct.textContent=value+'%';await new Promise(resolve=>setTimeout(resolve,420))}renderGeneratedBoard(plan);select(plan[0].id);bar.style.width='100%';pct.textContent='100%';text.textContent='PCB Generated';$('#checkStatus').textContent=`${plan.length+3} passed`;setTimeout(()=>{progress.classList.add('hidden');btn.disabled=false;text.textContent='Generate PCB';toast(`${plan.length} components placed — USB-C locked to board edge`)},750)};

$('#placementSend').onclick=applyPlacementCommand;
$('#placementInput').addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();applyPlacementCommand()}});

function updateConnections(){const board=$('#board');if(!board.classList.contains('generated'))return;let layer=board.querySelector('.connection-layer');if(!layer){layer=document.createElementNS('http://www.w3.org/2000/svg','svg');layer.setAttribute('class','connection-layer');layer.setAttribute('viewBox','0 0 100 100');layer.setAttribute('preserveAspectRatio','none');board.prepend(layer)}const entries=$$('.generated-part').map(el=>({el,id:el.dataset.part,x:parseFloat(el.style.getPropertyValue('--x')),y:parseFloat(el.style.getPropertyValue('--y'))}));const core=entries.find(item=>/controller|MCU/i.test(parts[item.id]?.name||''))||entries[0];if(!core)return;layer.innerHTML='';entries.filter(item=>item!==core).forEach(item=>{const middle=(item.x+core.x)/2;const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',`M ${item.x} ${item.y} L ${middle} ${item.y} L ${middle} ${core.y} L ${core.x} ${core.y}`);if(/USB|BQ24074|charger|regulator/i.test(parts[item.id]?.name||''))path.setAttribute('class','power-link');layer.append(path)})}
function applyPlacementCommand(){const input=$('#placementInput'),reply=$('#chatReply'),command=input.value.trim();const findPart=term=>{const q=term.toLowerCase().replace(/^the\s+/,'').trim();return Object.entries(parts).find(([,p])=>p.name.toLowerCase()===q)||Object.entries(parts).find(([,p])=>p.name.toLowerCase().includes(q))};const swap=command.match(/^\s*(?:switch|swap)(?:\s+places?\s+of)?\s+(.+?)\s+(?:and|with)\s+(.+?)\s*$/i);if(swap){const a=findPart(swap[1]),b=findPart(swap[2]);if(!a||!b){reply.textContent='I could not find both components. Use the names from Proposed components.';return}if(/USB-C/i.test(a[1].name)||/USB-C/i.test(b[1].name)){reply.textContent='USB-C remains at the edge so charging stays accessible.';return}const aEl=$(`.pcb-part[data-part="${a[0]}"]`),bEl=$(`.pcb-part[data-part="${b[0]}"]`);if(!aEl||!bEl){reply.textContent='Generate a PCB first, then ask me to switch components.';return}const ax=aEl.style.getPropertyValue('--x'),ay=aEl.style.getPropertyValue('--y');aEl.style.setProperty('--x',bEl.style.getPropertyValue('--x'));aEl.style.setProperty('--y',bEl.style.getPropertyValue('--y'));bEl.style.setProperty('--x',ax);bEl.style.setProperty('--y',ay);select(a[0]);updateConnections();reply.textContent=`Switched ${a[1].name} and ${b[1].name}; traces were re-routed automatically.`;input.value='';return}const move=command.match(/^\s*move\s+(.+?)\s+(on top of|above|below|under|left of|right of)\s+(.+?)\s*$/i);if(!move){reply.textContent='Try “Move Button 1 right of Button 4” or “Switch Button 1 and Button 2.”';return}const source=findPart(move[1]),target=findPart(move[3]);if(!source||!target){reply.textContent='I could not find one of those components. Use the name shown in Proposed components.';return}if(/USB-C/i.test(source[1].name)){reply.textContent='USB-C stays on the board edge for charging access.';return}const sourceEl=$(`.pcb-part[data-part="${source[0]}"]`),targetEl=$(`.pcb-part[data-part="${target[0]}"]`);if(!sourceEl||!targetEl){reply.textContent='Generate a PCB first, then ask me to move components.';return}let x=parseFloat(targetEl.style.getPropertyValue('--x')),y=parseFloat(targetEl.style.getPropertyValue('--y')),direction=move[2].toLowerCase();if(direction==='above'||direction==='on top of')y-=14;if(direction==='below'||direction==='under')y+=14;if(direction==='left of')x-=14;if(direction==='right of')x+=14;sourceEl.style.setProperty('--x',`${Math.max(12,Math.min(88,x))}%`);sourceEl.style.setProperty('--y',`${Math.max(12,Math.min(88,y))}%`);select(source[0]);updateConnections();reply.textContent=`Moved ${source[1].name} ${direction} ${target[1].name}; connected traces were re-routed.`;input.value=''}
$('#placementSend').onclick=applyPlacementCommand;
document.addEventListener('click',event=>{const part=event.target.closest('.generated-part');if(!part)return;const detail=parts[part.dataset.part];if(!detail)return;if(/button|joystick/i.test(detail.name)){part.classList.add('pressed');setTimeout(()=>part.classList.remove('pressed'),180);const action=/button/i.test(detail.name)?`${detail.name} pressed`:'Joystick input selected';$('.board-status').innerHTML=`<span><i class="pulse"></i> ${action}</span><span>Signal routed to controller</span>`;toast(`${action} — input signal received`)}});
$('#resetPcbBtn').onclick=()=>{selected=null;$('#prompt').value='';$('#board').className='board empty';$('#board').innerHTML='';$('#callout').classList.add('hidden');$('#leaderPath').closest('.leader').classList.add('hidden');componentList.innerHTML='<div class="empty-state">Describe any size PCB and every part you need. KeshComponents will build a new layout.</div>';library.innerHTML='';$('#componentCount').textContent='0';$('.strip-title span').textContent='0 placed';$('.board-status').innerHTML='<span><i class="pulse"></i> Ready for a new PCB</span>';$('#checkStatus').textContent='Waiting';$('#optTitle').textContent='No layout yet';$('#optBadge').textContent='Ready';$('#optCopy').textContent='Start a new design to receive a compactness score and placement recommendations.';toast('PCB reset — ready for a new design')};
